### PR TITLE
add communication over Unix Domain Socket

### PR DESCRIPTION
**Pull request by bernard357**
Hello there, this is a contribution so that Chistera Pi can be efficiently used in pure Python environment. The idea is that the sender can fetch data over a local socket, and the receiver can push data over a local socket. The other side of the socket can be written in any language, including Python.

python program --> socket --> uds_sender --> LoRa

LoRa --> uds_receiver --> socket --> python program

This has been developed for [the No-Picture Camera project](http://www.slideshare.net/bernard357/the-nopicture-camera) and you can expect full code and documentation to be released on GitHub soon.

### CODE REVIEW

**Comment by bernard357** [comment]
At this stage the software is working as expected. It has been used successfully to transmit measurements across 2 Raspberry Pi equipped with Chistera-Pi shields. The UDS sender has been installed as a service on the device that is counting people and faces. The UDS receiver has been installed on the device that is updating the database. Time for a merge for this PR?

**Comment by bernard357** [comment]
Please note that this software has been integrated into a larger experimentation around smart cameras. Thanks for any feedback on related [setup instructions](https://github.com/bernard357/smart-video-counter/blob/master/docs/setup.lora.md)

**Comment by Beetix** [comment]
Hi Bernard,

Sorry for the delay...

I have successfully tested the communication between 2 Raspberry Pi.

Thank you for your contribution! It's always nice to have new examples.

**Comment by bernard357** [comment]
Glad that you found this useful. And thanks for the feedback.

**Pull request merged**
